#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config\routes.yaml
controllers:
  resource: ../src/Controller/
  type: annotation

api_login_check:
  path: /api/login_check